### ISSUE TITLE
Ajouter des exemples de lecture de données spatiale web

### ISSUE THREAD

**Issue by jengelaere** [MTES-MCT/parcours_r_module_analyse_spatiale#29]
flux WFS
dido
flux IGN
BAN

**Comment by jdlom** [comment]
@jengelaere t'entends quoi par flux IGN ?
chargement d'un flux wms par exemple ?

**Comment by jengelaere** [comment]
Je crois que c'était plutôt les FTP

**Comment by jdlom** [comment]
@jengelaere je vois pas trop quoi ? si tu as une ressource en tête ?

**Comment by jengelaere** [comment]
https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_WGS84G_PACK_2022-04-15$ADMIN-EXPRESS-COG_3-1__SHP_WGS84G_FRA_2022-04-15/file/ADMIN-EXPRESS-COG_3-1__SHP_WGS84G_FRA_2022-04-15.7z par exemple

**Comment by jengelaere** [comment]
Je regarde si j'avais pas implémenté sur la branche 30, ça me dit qqchose cette histoire

**Comment by jengelaere** [comment]
En tout cas ça doit être déjà dans le M2

**Comment by jengelaere** [comment]
https://github.com/MTES-MCT/parcours_r_socle_preparation_des_donnees/blob/master/04-lire_des_donnees.Rmd#L167

**Comment by jengelaere** [comment]
C'est pas dans ma branche https://github.com/MTES-MCT/parcours_r_module_analyse_spatiale/tree/30_adapter_bien_commencer
