### ISSUE TITLE
8.1 Plus de warning avec st_buffer sur projections non métriques

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/parcours_r_module_analyse_spatiale#37]
Le warning concernant les buffer sur des projections en lon, lat ne semble plus être présent.
De plus, le buffer semble correct.

https://mtes-mct.github.io/parcours_r_module_analyse_spatiale/les-reprojections.html#un-premier-exemple-de-reprojection

```{r,warning=T}
library(sf)
library(mapview)
nantes<-data.frame(lon=-1.553621,lat=47.218371) %>% 
    st_as_sf(coords = c("lon", "lat")) %>% 
  st_set_crs(4326)

nantes_buffer= st_buffer(nantes, dist = 19000)
nantes_proj_buffer= st_buffer(st_transform(nantes, 2154), dist = 19000)

mapview(list(nantes,nantes_buffer,nantes_proj_buffer))
```

**Comment by jdlom** [comment]
@jengelaere que fait-on ?

**Comment by jengelaere** [comment]
Je regarde ça début de semaine @jdlom suis en vadrouille

**Comment by jengelaere** [comment]
je peux adapter la formulation dans la branche 30 adapter bien commencé, j'avais en stocks plusieurs correction de coquille et d'adaptation du support aux évolutions des packages, je finalise cette semaine et te refais lire ? Tu n'as pas une branche du même type sur ton PC ?

**Comment by jengelaere** [comment]
Je viens de voir https://github.com/MTES-MCT/parcours_r_module_analyse_spatiale/pull/38 
Tu ne peux pas travailler sur ce repos dans une branche à toi que travailles depuis ton name space ?

**Comment by jdlom** [comment]
> Je viens de voir #38 Tu ne peux pas travailler sur ce repos dans une branche à toi et que travailles depuis ton name space ?

En français :) ? Tu veux que je travaille sur le repo au lieu de travailler chez moi ?

**Comment by jengelaere** [comment]
oui, c'était vraiment pas clair mais t'as compris

**Comment by jengelaere** [comment]
Je peux pas la comparer à mes travaux et voir les conflits avec ma branche local si ta branche n'est pas sur ce repo

**Comment by jengelaere** [comment]
c'est je crois ce que Maël voulait dire dans #8 
Toute cette partie sur la mauvaise gestion des lon lat par R peut être enlevée a priori, plus besoin de s'en préoccuper

**Comment by MaelTheuliere** [comment]
Hello les anciens collègues, je confirme pour le premier lien du #8 le deuxième est relatif à la structuration du CRS qui a changé et qui est d'ailleurs de mémoire peux explicité dans le support...

**Comment by jengelaere** [comment]
Merci Maël !

**Comment by jengelaere** [comment]
Adaptation réalisée dans le commit efd5dc77521861a2b887232daef1ce0fcdd2f366
